name: SportsScores
options:
  bundleIdPrefix: com.sportsscores
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    DEVELOPMENT_TEAM: ""

targets:
  SportsScores:
    type: application
    platform: macOS
    sources:
      - path: SportsScores
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sportsscores.app
        PRODUCT_NAME: SportsScores
        INFOPLIST_FILE: SportsScores/Info.plist
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_STYLE: Automatic
        COMBINE_HIDPI_IMAGES: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_HARDENED_RUNTIME: true
        ENABLE_APP_SANDBOX: true
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
    info:
      path: SportsScores/Info.plist
      properties:
        CFBundleName: SportsScores
        CFBundleDisplayName: Sports Scores
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        LSUIElement: false
        NSHighResolutionCapable: true
        NSHumanReadableCopyright: "Copyright © 2024. All rights reserved."
    entitlements:
      path: SportsScores/SportsScores.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
